package NumSequence;

public class L_389_FindTheDifference {

    /*
        Given two strings s and t which consist of only lowercase letters.

        String t is generated by random shuffling string s and then add one
        more letter at a random position.

        Find the letter that was added in t.

        Example:
            Input:
            s = "abcd"
            t = "abcde"
            Output:
            e
            Explanation:
            'e' is the letter that was added.

     */

    public static void main(String[] args) {
        L_389_FindTheDifference l = new L_389_FindTheDifference();
        String s = "abcd";
        String t = "abcde";
        System.out.println(l.findTheDifference(s, t));
    }

    public char findTheDifference(String s, String t) {
        return findTheDifference3(s, t);
    }

    public char findTheDifference1(String s, String t) {
        int[] chs = new int[26];
        for (int i = 0; i < s.length(); i++) {
            ++chs[s.charAt(i) - 'a'];
        }
        for (int i = 0; i < t.length(); i++) {
            if (0 == chs[t.charAt(i) - 'a']) return t.charAt(i);
            else --chs[t.charAt(i) - 'a'];
        }
        return ' ';
    }

    // inspired by Discuss
    public char findTheDifference2(String s, String t) {
        int snum = 0;
        int tnum = 0;
        for (int i = 0; i < s.length(); i++) {
            snum += s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            tnum += t.charAt(i);
        }
        return (char) (tnum - snum);
    }

    // inspired by Discuss
    public char findTheDifference3(String s, String t) {
        byte result = 0;
        for (int i = 0; i < s.length(); i++) {
            result ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            result ^= t.charAt(i);
        }
        return (char) result;
    }


}
